# Generated by Django 2.2.6 on 2019-11-21 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiakat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
