# Generated by Django 2.2.6 on 2019-11-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saiakat', '0002_destinations_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='News/pics')),
            ],
        ),
    ]
